name: CI build workflow with MISE-EN-PLACE

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.7'

      - name: Install Mise and Dependencies
        uses: jdx/mise-action@v2
        with:
          version: 2025.10.2
          install: true
          cache: true

      - name: Trust mise configuration
        run: |
          chmod +x scripts/trust-mise.sh || true
          bash scripts/trust-mise.sh
        continue-on-error: false

      - name: Run build via Mise
        run: |
          mise run build

      - name: Upload coverage XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: tests/coverage/coverage.xml

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: tests/coverage/html

      - name: Create run summary and append to UI summary
        if: always()
        run: |
          RUN_SUMMARY_FILE="$GITHUB_WORKSPACE/run-summary.md"
          echo "# Run summary for ${GITHUB_REPOSITORY}" > "$RUN_SUMMARY_FILE"
          echo "" >> "$RUN_SUMMARY_FILE"
          echo "- Run number: ${GITHUB_RUN_NUMBER}" >> "$RUN_SUMMARY_FILE"
          echo "- Run ID: ${GITHUB_RUN_ID}" >> "$RUN_SUMMARY_FILE"
          echo "- Trigger: ${GITHUB_EVENT_NAME}" >> "$RUN_SUMMARY_FILE"
          echo "- Commit: ${GITHUB_SHA}" >> "$RUN_SUMMARY_FILE"
          echo "- Actor: ${GITHUB_ACTOR}" >> "$RUN_SUMMARY_FILE"
          echo "" >> "$RUN_SUMMARY_FILE"
          echo "## Artifacts" >> "$RUN_SUMMARY_FILE"
          echo "- Actions artifacts page: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> "$RUN_SUMMARY_FILE"
          echo "" >> "$RUN_SUMMARY_FILE"
          if [ -f tests/coverage/coverage.xml ]; then
            echo "## Coverage reports" >> "$RUN_SUMMARY_FILE"
            echo "- Coverage XML: tests/coverage/coverage.xml" >> "$RUN_SUMMARY_FILE"
            echo "- Coverage HTML directory: tests/coverage/html" >> "$RUN_SUMMARY_FILE"
          fi
          echo "" >> "$RUN_SUMMARY_FILE"
          # Append a small link to the GitHub run summary UI
          echo "## Build artifacts" >> "$GITHUB_STEP_SUMMARY"
          echo "- [Download run summary](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID})" >> "$GITHUB_STEP_SUMMARY"

      - name: Upload run summary artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-summary
          path: run-summary.md
